import:
  - catalog/terraform-backend

vars:
  stage: qa
  location: eastus
  resource_group_name: "kml_rg_main-5d1ac0f7869848de" # Asumimos que el RG ya existe
  subscription_id: "a2b28c85-1948-4263-90ca-bade2bac4df4"

components:
  terraform:
    # 1. Monitoreo
    app-insights-dev:
      metadata:
        component: app-insights
      vars:
        name: "appi-orders-qa-001"

    # 2. Almacenamiento
    storage-orders-dev:
      metadata:
        component: storage-account
      vars:
        name: "stordersqa001"

    # 3. Plan de Servicio
    plan-orders-dev:
      metadata:
        component: service-plan
      vars:
        name: "plan-orders-qa-001"

    # 4. Azure Function (El consumidor)
    function-orders-dev:
      metadata:
        component: azure-function
      vars:
        name: "func-orders-qa-001"
        # Aquí conectamos los puntos: pasamos los nombres exactos de arriba
        app_insights_name: "appi-orders-qa-001"
        storage_account_name: "stordersqa001"
        service_plan_name: "plan-orders-qa-001"
